CREATE TABLE IF NOT EXISTS PERSON ( 
	ID INT NOT NULL AUTO_INCREMENT, 
	FIRST_NAME VARCHAR (50) NULL, 
	LAST_NAME VARCHAR (50) NULL,
	EMAIL VARCHAR (100) NULL,
	CREATED_TS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	CONSTRAINT PRIMARY KEY (ID));
